apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apiserver
  - ../../controller-manager

images:
  - name: knowledge-apiserver
    newName: knowledge
    newTag: dev
  - name: knowledge-controller-manager
    newName: knowledge
    newTag: dev
