//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneContextRef) DeepCopyInto(out *ControlPlaneContextRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneContextRef.
func (in *ControlPlaneContextRef) DeepCopy() *ControlPlaneContextRef {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneContextRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceEndpoint) DeepCopyInto(out *ResourceEndpoint) {
	*out = *in
	out.ControlPlaneContextRef = in.ControlPlaneContextRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceEndpoint.
func (in *ResourceEndpoint) DeepCopy() *ResourceEndpoint {
	if in == nil {
		return nil
	}
	out := new(ResourceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipType) DeepCopyInto(out *RelationshipType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipType.
func (in *RelationshipType) DeepCopy() *RelationshipType {
	if in == nil {
		return nil
	}
	out := new(RelationshipType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelationshipType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipTypeList) DeepCopyInto(out *RelationshipTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RelationshipType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipTypeList.
func (in *RelationshipTypeList) DeepCopy() *RelationshipTypeList {
	if in == nil {
		return nil
	}
	out := new(RelationshipTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelationshipTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipTypeSpec) DeepCopyInto(out *RelationshipTypeSpec) {
	*out = *in
	out.SubjectGVK = in.SubjectGVK
	out.ObjectGVK = in.ObjectGVK
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipTypeSpec.
func (in *RelationshipTypeSpec) DeepCopy() *RelationshipTypeSpec {
	if in == nil {
		return nil
	}
	out := new(RelationshipTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipTypeStatus) DeepCopyInto(out *RelationshipTypeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipTypeStatus.
func (in *RelationshipTypeStatus) DeepCopy() *RelationshipTypeStatus {
	if in == nil {
		return nil
	}
	out := new(RelationshipTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSelector) DeepCopyInto(out *SubjectSelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSelector.
func (in *SubjectSelector) DeepCopy() *SubjectSelector {
	if in == nil {
		return nil
	}
	out := new(SubjectSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverySpec) DeepCopyInto(out *DiscoverySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverySpec.
func (in *DiscoverySpec) DeepCopy() *DiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipPolicySpec) DeepCopyInto(out *RelationshipPolicySpec) {
	*out = *in
	out.RelationshipType = in.RelationshipType
	in.Subject.DeepCopyInto(&out.Subject)
	out.Discovery = in.Discovery
	out.ControlPlaneContextRef = in.ControlPlaneContextRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipPolicySpec.
func (in *RelationshipPolicySpec) DeepCopy() *RelationshipPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RelationshipPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipPolicyStatus) DeepCopyInto(out *RelationshipPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipPolicyStatus.
func (in *RelationshipPolicyStatus) DeepCopy() *RelationshipPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RelationshipPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipPolicy) DeepCopyInto(out *RelationshipPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipPolicy.
func (in *RelationshipPolicy) DeepCopy() *RelationshipPolicy {
	if in == nil {
		return nil
	}
	out := new(RelationshipPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelationshipPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipPolicyList) DeepCopyInto(out *RelationshipPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RelationshipPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipPolicyList.
func (in *RelationshipPolicyList) DeepCopy() *RelationshipPolicyList {
	if in == nil {
		return nil
	}
	out := new(RelationshipPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelationshipPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipSource) DeepCopyInto(out *RelationshipSource) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipSource.
func (in *RelationshipSource) DeepCopy() *RelationshipSource {
	if in == nil {
		return nil
	}
	out := new(RelationshipSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRelationshipSpec) DeepCopyInto(out *ResourceRelationshipSpec) {
	*out = *in
	out.RelationshipType = in.RelationshipType
	out.Subject = in.Subject
	out.Object = in.Object
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRelationshipSpec.
func (in *ResourceRelationshipSpec) DeepCopy() *ResourceRelationshipSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceRelationshipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRelationshipStatus) DeepCopyInto(out *ResourceRelationshipStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRelationshipStatus.
func (in *ResourceRelationshipStatus) DeepCopy() *ResourceRelationshipStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceRelationshipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRelationship) DeepCopyInto(out *ResourceRelationship) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRelationship.
func (in *ResourceRelationship) DeepCopy() *ResourceRelationship {
	if in == nil {
		return nil
	}
	out := new(ResourceRelationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRelationship) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRelationshipList) DeepCopyInto(out *ResourceRelationshipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceRelationship, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRelationshipList.
func (in *ResourceRelationshipList) DeepCopy() *ResourceRelationshipList {
	if in == nil {
		return nil
	}
	out := new(ResourceRelationshipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRelationshipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraversalSpec) DeepCopyInto(out *TraversalSpec) {
	*out = *in
	if in.RelationshipTypes != nil {
		in, out := &in.RelationshipTypes, &out.RelationshipTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraversalSpec.
func (in *TraversalSpec) DeepCopy() *TraversalSpec {
	if in == nil {
		return nil
	}
	out := new(TraversalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphNode) DeepCopyInto(out *GraphNode) {
	*out = *in
	out.Endpoint = in.Endpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphNode.
func (in *GraphNode) DeepCopy() *GraphNode {
	if in == nil {
		return nil
	}
	out := new(GraphNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphEdge) DeepCopyInto(out *GraphEdge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphEdge.
func (in *GraphEdge) DeepCopy() *GraphEdge {
	if in == nil {
		return nil
	}
	out := new(GraphEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQuerySpec) DeepCopyInto(out *GraphQuerySpec) {
	*out = *in
	out.Root = in.Root
	in.Traverse.DeepCopyInto(&out.Traverse)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQuerySpec.
func (in *GraphQuerySpec) DeepCopy() *GraphQuerySpec {
	if in == nil {
		return nil
	}
	out := new(GraphQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQueryStatus) DeepCopyInto(out *GraphQueryStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]GraphNode, len(*in))
		copy(*out, *in)
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]GraphEdge, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQueryStatus.
func (in *GraphQueryStatus) DeepCopy() *GraphQueryStatus {
	if in == nil {
		return nil
	}
	out := new(GraphQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQuery) DeepCopyInto(out *GraphQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQuery.
func (in *GraphQuery) DeepCopy() *GraphQuery {
	if in == nil {
		return nil
	}
	out := new(GraphQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQueryList) DeepCopyInto(out *GraphQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQueryList.
func (in *GraphQueryList) DeepCopy() *GraphQueryList {
	if in == nil {
		return nil
	}
	out := new(GraphQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
